### ISSUE TITLE
dotnet core support

### ISSUE THREAD

**Issue by wklm** [Ian144/fsFixGen#1]
Hey @Ian144,

many thanks for making this project public. Are you planning to migrate it to dotnet core? 

cheers,
Wojtek

**Comment by Ian144** [comment]
Hi Wojtec,

I may migrate to .netcore sometime, but I don’t know when. Finding time for these things is difficult.

Thanks, Ian

On 25 Dec 2017, at 07:50, Wojtek <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @Ian144<https://github.com/ian144>,

many thanks for making this project public. Are you planning to migrate it to dotnet core?

cheers,
Wojtek

**Comment by wklm** [comment]
I would be happy to help! I saw some todos in the source code. Would you find some time to turn them into github issues, so it would be easier to organize and contribute?

**Comment by Ian144** [comment]
Hi Wojtek,

Thanks for the offer. I am on holiday at the moment, but I get  back home in a day or two. I will see what I can to before starting work again.

thanks, Ian
________________________________

**Comment by dm3** [comment]
Hey, I'm also very interested in this project supporting .NET Core!

However, I'm very new to the .NET ecosystem and have no idea where to start looking in order to implement the support without expending unnecessary effort. Would be great if you could outline the steps needed, @Ian144!

Also, if there are known problems, unimplemented critical features and stuff like that - would be great to have them as Github issues. What do you think?

**Comment by MatthiasWeiser** [comment]
Since FxFIX is a library one should look at porting it to .NET standard.
Then one can use the library either from the classic .NET framework or from .NET core.
As the library has no external dependencies than FSharp.Core, this should be more a build environment than an actual programming task.

**Comment by Ian144** [comment]
I have created a public FsFIX.netstandard repo. I've removed the Echo and ReverseGen projects, and some work i had started but not got very far with on Acceptors and Initiators. All property and unit tests pass, and benchmarks usually a bit faster under .netstandard, but I did this in a hurry so I would not be surprised if i've forgotten something
